service: serverless-reminders

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource:
        - "*"

functions:
  dailyReminder:
    handler: handler.sendReminderDaily
    events:
      - schedule: rate(1 day)
  weekendReminder:
    handler: handler.sendReminderWeekend
    events:
      - schedule: cron(30 22 ? * SUN,SAT *)
